extends Node

# Simple sound bank — loads WAVs from assets/sounds/ and plays them on
# demand via a pool of AudioStreamPlayer3D voices parented to a node of
# your choice. All sounds are synthesized by tools/gen_clean_sfx.py.

const SOUNDS_DIR := "res://assets/sounds"

# Clean-room SFX files generated by tools/gen_clean_sfx.py. Every name
# here maps 1:1 to an audio file on disk. Aliases let the game code keep
# requesting evocative names ("death", "star_get", "backflip") and get
# routed to whichever file fits.
const SOUND_NAMES := [
    "jump", "double_jump", "triple_jump",
    "land", "land_hard", "ground_pound", "step",
    "coin", "coin_red", "star_get", "oneup", "cap_get",
    "hurt", "death", "enemy_squish", "bomb_explode",
    "pause", "warp",
    # BGM aliases — the sound-gen script doesn't write music yet, so
    # play_bgm silently no-ops until that's added.
    "bgm_castle", "bgm_course", "bgm_water", "bgm_bowser", "bgm_sub",
]

const SOUND_ALIASES := {
    # Legacy game-code names → their equivalent clean-room sound.
    "yahoo":       "triple_jump",
    "yah":         "jump",
    "haha":        "double_jump",
    "whoa":        "death",
    "attacked":    "hurt",
    "ooof":        "hurt",
    "plop":        "land",
    "heavy_land":  "land_hard",
    "punch":       "enemy_squish",
    "damage":      "hurt",
    "title":       "coin",
    "star_yahoo":  "star_get",
    "long_jump":   "triple_jump",
    "backflip":    "double_jump",
    "wall_kick":   "jump",
    "dive":        "jump",
    "star":        "star_get",
    "cap":         "cap_get",
}

const SOUND_BANKS := {
    "jump": ["jump"],
    "land": ["land", "land_hard"],
}

var _streams: Dictionary = {}
var _players: Array[AudioStreamPlayer3D] = []
var _pool_idx: int = 0
var _bgm_player: AudioStreamPlayer   # 2D/global for background music
var _bgm_current: String = ""


func setup(voice_count: int, mount: Node3D) -> void:
    for name in SOUND_NAMES:
        if SOUND_ALIASES.has(name):
            continue  # alias resolved at play() time
        var path := "%s/%s.wav" % [SOUNDS_DIR, name]
        if not FileAccess.file_exists(path):
            continue
        var stream := _load_wav(path)
        if stream != null:
            _streams[name] = stream
    for _i in range(voice_count):
        var p := AudioStreamPlayer3D.new()
        p.unit_size = 6.0
        mount.add_child(p)
        _players.append(p)
    # Global BGM player, non-positional, plays looped music.
    _bgm_player = AudioStreamPlayer.new()
    _bgm_player.volume_db = -8.0
    mount.add_child(_bgm_player)


func play_bgm(track: String) -> void:
    if track == _bgm_current:
        return
    _bgm_current = track
    var s: Variant = _streams.get(track)
    if s == null:
        _bgm_player.stop()
        return
    # Enable the loop flag on the stream so AudioStreamPlayer repeats it.
    s.loop_mode = AudioStreamWAV.LOOP_FORWARD
    s.loop_begin = 0
    s.loop_end = s.data.size() / (2 if s.format == AudioStreamWAV.FORMAT_16_BITS else 1)
    _bgm_player.stream = s
    _bgm_player.play()


func stop_bgm() -> void:
    if _bgm_player != null:
        _bgm_player.stop()
        _bgm_current = ""


func _load_wav(path: String) -> AudioStreamWAV:
    # Parse the WAV header ourselves so we handle whatever sample rate /
    # bit depth / channel count the source produced, rather than assuming
    # 22 kHz mono. Returns null on anything non-PCM or malformed.
    var bytes := FileAccess.get_file_as_bytes(path)
    if bytes.size() < 44 or bytes.slice(0, 4) != PackedByteArray([0x52,0x49,0x46,0x46]):
        return null
    if bytes.slice(8, 12) != PackedByteArray([0x57,0x41,0x56,0x45]):
        return null
    var sample_rate: int = 22050
    var bits: int = 16
    var channels: int = 1
    var data_offset: int = -1
    var data_size: int = 0
    var i: int = 12
    while i + 8 <= bytes.size():
        var chunk_id: PackedByteArray = bytes.slice(i, i + 4)
        var chunk_size: int = bytes.decode_u32(i + 4)
        if chunk_id == PackedByteArray([0x66,0x6D,0x74,0x20]):  # "fmt "
            # var fmt_tag := bytes.decode_u16(i + 8)       # 1 = PCM
            channels = bytes.decode_u16(i + 10)
            sample_rate = bytes.decode_u32(i + 12)
            bits = bytes.decode_u16(i + 22)
        elif chunk_id == PackedByteArray([0x64,0x61,0x74,0x61]):  # "data"
            data_offset = i + 8
            data_size = chunk_size
            break
        i += 8 + chunk_size
    if data_offset < 0:
        return null

    var stream := AudioStreamWAV.new()
    stream.mix_rate = sample_rate
    stream.stereo = (channels == 2)
    match bits:
        8:  stream.format = AudioStreamWAV.FORMAT_8_BITS
        16: stream.format = AudioStreamWAV.FORMAT_16_BITS
        _:  return null
    stream.data = bytes.slice(data_offset, data_offset + data_size)
    return stream


func play(name: String) -> void:
    var actual: String = name
    if SOUND_BANKS.has(name):
        var bank: Array = SOUND_BANKS[name]
        actual = bank[randi() % bank.size()]
    else:
        actual = SOUND_ALIASES.get(name, name)
    var s: Variant = _streams.get(actual)
    if s == null:
        return
    if _players.is_empty():
        return
    var p := _players[_pool_idx % _players.size()]
    _pool_idx += 1
    p.stream = s
    # Small pitch variance so repeated plays don't sound identical even
    # when the bank resolves to the same clip.
    p.pitch_scale = 0.95 + randf() * 0.1
    p.play()
